### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshi2912**

### CODE REVIEW

**Comment by sakshi2912** [comment]
!bounty 12

**Comment by sakshi2912** [comment]
!bounty 10

**Comment by srujandeshpande** [comment]
!bounty 1

**Comment by sakshi2912** [comment]
!bounty 2

**Comment by arjunvuppala123** [comment]
!bounty 1

**Comment by sakshi2912** [comment]
!bounty 1

**Comment by srujandeshpande** [comment]
!bounty 1

**Comment by srujandeshpande** [comment]
!bounty 1

**Comment by arjunvuppala123** [comment]
!bounty 1

**Comment by sakshi2912** [comment]
!bounty 1

**Comment by srujandeshpande** [comment]
!bounty 2 amazing?

**Comment by arjunvuppala123** [comment]
!bounty 10

**Pull request closed without merging**
